#!/usr/bin/env bash
# Uninstall the cell datasource helper, plugin, and autosetup services.
# Usage: ./uninstall.sh [--keep-config] [--remove-kismet]
# Defaults: keep Kismet and its configs; remove only the cell bits and autosetup units.

set -euo pipefail

PREFIX="${PREFIX:-/usr}"
KEEP_CONFIG=0
REMOVE_KISMET=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep-config) KEEP_CONFIG=1 ;;
    --remove-kismet) REMOVE_KISMET=1 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

BIN_DIR="${PREFIX}/bin"
PLUGIN_DIR="${PREFIX}/lib/kismet/cell"
JS_DIR="${PLUGIN_DIR}/httpd/js"
CONFIG_DIR="/etc/kismet"
CONFIG_DS_DIR="${CONFIG_DIR}/datasources.d"
SERVICE_PATH="/etc/systemd/system/kismet-cell-autosetup.service"
TIMER_PATH="/etc/systemd/system/kismet-cell-autosetup.timer"
KISMET_SERVICE="/etc/systemd/system/kismet.service"
KISMET_DROPIN="/etc/systemd/system/kismet.service.d/override.conf"

log() { printf '[uninstall] %s\n' "$*"; }

log "Uninstalling cell datasource"

# Stop/disable services
if command -v systemctl >/dev/null 2>&1; then
  if systemctl list-unit-files | grep -q '^kismet-cell-autosetup.timer'; then
    log "Stopping/disabling kismet-cell-autosetup.timer"
    systemctl stop kismet-cell-autosetup.timer || true
    systemctl disable kismet-cell-autosetup.timer || true
  fi
  if systemctl list-unit-files | grep -q '^kismet-cell-autosetup.service'; then
    log "Stopping/disabling kismet-cell-autosetup.service"
    systemctl stop kismet-cell-autosetup.service || true
    systemctl disable kismet-cell-autosetup.service || true
  fi
  if systemctl list-unit-files | grep -q '^kismet.service'; then
    log "Stopping/disabling kismet.service"
    systemctl stop kismet || true
    systemctl disable kismet || true
  fi
fi

# Remove autosetup service files
for unit in "${SERVICE_PATH}" "${TIMER_PATH}"; do
  if [[ -f "${unit}" ]]; then
    log "Removing ${unit}"
    rm -f "${unit}"
  fi
done

# Remove our kismet drop-in (restart policy)
if [[ -f "${KISMET_DROPIN}" ]]; then
  log "Removing ${KISMET_DROPIN}"
  rm -f "${KISMET_DROPIN}"
fi

# Remove kismet.service only if it matches our generated unit
if [[ -f "${KISMET_SERVICE}" ]]; then
  if grep -q "Kismet wireless IDS server" "${KISMET_SERVICE}" && grep -q "AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW" "${KISMET_SERVICE}"; then
    log "Removing generated ${KISMET_SERVICE}"
    rm -f "${KISMET_SERVICE}"
  else
    log "Preserving existing ${KISMET_SERVICE} (does not look generated by this installer)"
  fi
fi

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
fi

# Remove binaries/scripts
for f in "${BIN_DIR}/kismet_cap_cell_capture" \
         "${BIN_DIR}/multi_phone.sh" \
         "${BIN_DIR}/cell_autoconfig.sh" \
         "${BIN_DIR}/collector.py" \
         "${BIN_DIR}/uds_forwarder.py"; do
  if [[ -f "${f}" ]]; then
    log "Removing ${f}"
    rm -f "${f}"
  fi
done

# Remove plugin files
if [[ -d "${PLUGIN_DIR}" ]]; then
  for f in "${PLUGIN_DIR}/cell.so" "${PLUGIN_DIR}/manifest.conf"; do
    [[ -f "${f}" ]] && { log "Removing ${f}"; rm -f "${f}"; }
  done
  if [[ -d "${JS_DIR}" ]]; then
    for js in "${JS_DIR}/kismet.ui.cell.js"; do
      [[ -f "${js}" ]] && { log "Removing ${js}"; rm -f "${js}"; }
    done
  fi
  rmdir "${JS_DIR}" 2>/dev/null || true
  rmdir "${PLUGIN_DIR}" 2>/dev/null || true
fi

# Remove datasource config
if [[ ${KEEP_CONFIG} -eq 0 ]]; then
  CELL_CONF="${CONFIG_DS_DIR}/cell.conf"
  if [[ -f "${CELL_CONF}" ]]; then
    log "Removing ${CELL_CONF}"
    rm -f "${CELL_CONF}"
  fi
fi

if [[ ${REMOVE_KISMET} -eq 1 ]]; then
  if command -v apt-get >/dev/null 2>&1; then
    log "Removing Kismet packages"
    apt-get remove -y kismet kismet-core kismet-logtools || true
    apt-get autoremove -y || true
  fi
fi

log "Uninstall complete."
